import type { ComponentType, ReactNode } from 'react'
import type { BrandConfig } from '@/brands/types'
import { DEFAULT_THEME_ID } from './manifest'
import { THEME_CONTEXT_REGISTRY_GENERATED } from './generated/theme-context-registry.generated'

type BrandClientWrapperComponent = ComponentType<{
  children: ReactNode
  brand: BrandConfig
}>

type BrandStylesComponent = ComponentType<{ brand: BrandConfig }>
type AuthProviderComponent = ComponentType<{ children: ReactNode }>
type DynamicFaviconComponent = ComponentType<Record<string, never>>

export type ThemeContextBundle = {
  BrandClientWrapper: BrandClientWrapperComponent
  BrandStyles: BrandStylesComponent
  AuthProvider: AuthProviderComponent
  DynamicFavicon: DynamicFaviconComponent
}

// THEME_CONTEXT_REGISTRY is auto-generated by `tools/sync-theme-contracts.mjs`
// from the per-theme `context/` folders. Don't hand-edit the generated file —
// drop a new theme folder under `app/themes/<id>/` and run `npm run theme:sync`.
export const THEME_CONTEXT_REGISTRY: Record<string, ThemeContextBundle> =
  THEME_CONTEXT_REGISTRY_GENERATED

export function getThemeContextBundle(themeId: string): ThemeContextBundle {
  return THEME_CONTEXT_REGISTRY[themeId] || THEME_CONTEXT_REGISTRY[DEFAULT_THEME_ID]
}
