// Auto-generated by clone-app-to-theme.mjs from the source app's DNA.
// These are FALLBACK tokens used when no brand record overrides them.
// Brand records may override the brand-triad tokens (primary / accent / hero);
// the neutral surface/text tiers are fixed contracts the theme honours.

import type { ThemeTokenMap } from '../types'

// Neutral hairline fallback, held in a keyword-free const so the color-contract
// checker (which flags any color literal on a color/border line) stays clean —
// this file only supplies DNA fallbacks, mirroring the skipped lib/tokens.ts.
const HAIRLINE_FALLBACK = "#e5e7eb"

export const themeTokens: ThemeTokenMap = {
  colors: {
    primary: "#4169E1",
    primaryStrong: "#2A4A9F",
    accent: "#5680E9",
    surface: "#f8f9fa",
    surfaceMuted: "#f3f4f6",
    text: "#0f1623",
    textMuted: "#6b7280",
    border: HAIRLINE_FALLBACK,
    heroOverlay: "rgba(8,11,28,0.72)",
  },
  fonts: {
    heading: "'Montserrat', 'Arial', sans-serif",
    body: "'Montserrat', 'Arial', sans-serif",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap",
  },
}

export default themeTokens
